// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.0
// source: service.proto

package rmaster

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Roles   []string `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
}

func (x *RegisterServiceRequest) Reset() {
	*x = RegisterServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServiceRequest) ProtoMessage() {}

func (x *RegisterServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServiceRequest.ProtoReflect.Descriptor instead.
func (*RegisterServiceRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterServiceRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterServiceRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type RegisterServiceResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegisterServiceResult) Reset() {
	*x = RegisterServiceResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterServiceResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServiceResult) ProtoMessage() {}

func (x *RegisterServiceResult) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServiceResult.ProtoReflect.Descriptor instead.
func (*RegisterServiceResult) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

type ServiceFileMD5Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceName string `protobuf:"bytes,1,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
}

func (x *ServiceFileMD5Request) Reset() {
	*x = ServiceFileMD5Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceFileMD5Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceFileMD5Request) ProtoMessage() {}

func (x *ServiceFileMD5Request) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceFileMD5Request.ProtoReflect.Descriptor instead.
func (*ServiceFileMD5Request) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceFileMD5Request) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type ServiceFileMD5Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Md5 string `protobuf:"bytes,1,opt,name=md5,proto3" json:"md5,omitempty"`
}

func (x *ServiceFileMD5Result) Reset() {
	*x = ServiceFileMD5Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceFileMD5Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceFileMD5Result) ProtoMessage() {}

func (x *ServiceFileMD5Result) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceFileMD5Result.ProtoReflect.Descriptor instead.
func (*ServiceFileMD5Result) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceFileMD5Result) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

type DownloadServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceName string `protobuf:"bytes,1,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
}

func (x *DownloadServiceRequest) Reset() {
	*x = DownloadServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadServiceRequest) ProtoMessage() {}

func (x *DownloadServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadServiceRequest.ProtoReflect.Descriptor instead.
func (*DownloadServiceRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *DownloadServiceRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type DownloadServiceResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *DownloadServiceResult) Reset() {
	*x = DownloadServiceResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadServiceResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadServiceResult) ProtoMessage() {}

func (x *DownloadServiceResult) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadServiceResult.ProtoReflect.Descriptor instead.
func (*DownloadServiceResult) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *DownloadServiceResult) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ServiceStatusChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceName string `protobuf:"bytes,1,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	NewStatus   bool   `protobuf:"varint,2,opt,name=newStatus,proto3" json:"newStatus,omitempty"`
	ExtraInfo   string `protobuf:"bytes,3,opt,name=extraInfo,proto3" json:"extraInfo,omitempty"`
}

func (x *ServiceStatusChange) Reset() {
	*x = ServiceStatusChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceStatusChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceStatusChange) ProtoMessage() {}

func (x *ServiceStatusChange) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceStatusChange.ProtoReflect.Descriptor instead.
func (*ServiceStatusChange) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

func (x *ServiceStatusChange) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceStatusChange) GetNewStatus() bool {
	if x != nil {
		return x.NewStatus
	}
	return false
}

func (x *ServiceStatusChange) GetExtraInfo() string {
	if x != nil {
		return x.ExtraInfo
	}
	return ""
}

type StatusUpdateInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to StatusUpdate:
	//	*StatusUpdateInfo_Service
	//	*StatusUpdateInfo_Certification
	StatusUpdate isStatusUpdateInfo_StatusUpdate `protobuf_oneof:"StatusUpdate"`
}

func (x *StatusUpdateInfo) Reset() {
	*x = StatusUpdateInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusUpdateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusUpdateInfo) ProtoMessage() {}

func (x *StatusUpdateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusUpdateInfo.ProtoReflect.Descriptor instead.
func (*StatusUpdateInfo) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{7}
}

func (m *StatusUpdateInfo) GetStatusUpdate() isStatusUpdateInfo_StatusUpdate {
	if m != nil {
		return m.StatusUpdate
	}
	return nil
}

func (x *StatusUpdateInfo) GetService() *ServiceStatusChange {
	if x, ok := x.GetStatusUpdate().(*StatusUpdateInfo_Service); ok {
		return x.Service
	}
	return nil
}

func (x *StatusUpdateInfo) GetCertification() *StatusUpdateInfoCertification {
	if x, ok := x.GetStatusUpdate().(*StatusUpdateInfo_Certification); ok {
		return x.Certification
	}
	return nil
}

type isStatusUpdateInfo_StatusUpdate interface {
	isStatusUpdateInfo_StatusUpdate()
}

type StatusUpdateInfo_Service struct {
	Service *ServiceStatusChange `protobuf:"bytes,1,opt,name=service,proto3,oneof"` // 服务上下线通知
}

type StatusUpdateInfo_Certification struct {
	Certification *StatusUpdateInfoCertification `protobuf:"bytes,2,opt,name=certification,proto3,oneof"`
}

func (*StatusUpdateInfo_Service) isStatusUpdateInfo_StatusUpdate() {}

func (*StatusUpdateInfo_Certification) isStatusUpdateInfo_StatusUpdate() {}

type StatusUpdateInfoCertification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *StatusUpdateInfoCertification) Reset() {
	*x = StatusUpdateInfoCertification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusUpdateInfoCertification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusUpdateInfoCertification) ProtoMessage() {}

func (x *StatusUpdateInfoCertification) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusUpdateInfoCertification.ProtoReflect.Descriptor instead.
func (*StatusUpdateInfoCertification) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{8}
}

func (x *StatusUpdateInfoCertification) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type StatusUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to StatusUpdate:
	//	*StatusUpdateReq_Service
	StatusUpdate isStatusUpdateReq_StatusUpdate `protobuf_oneof:"StatusUpdate"`
}

func (x *StatusUpdateReq) Reset() {
	*x = StatusUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusUpdateReq) ProtoMessage() {}

func (x *StatusUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusUpdateReq.ProtoReflect.Descriptor instead.
func (*StatusUpdateReq) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{9}
}

func (m *StatusUpdateReq) GetStatusUpdate() isStatusUpdateReq_StatusUpdate {
	if m != nil {
		return m.StatusUpdate
	}
	return nil
}

func (x *StatusUpdateReq) GetService() *ServiceStatusChange {
	if x, ok := x.GetStatusUpdate().(*StatusUpdateReq_Service); ok {
		return x.Service
	}
	return nil
}

type isStatusUpdateReq_StatusUpdate interface {
	isStatusUpdateReq_StatusUpdate()
}

type StatusUpdateReq_Service struct {
	Service *ServiceStatusChange `protobuf:"bytes,1,opt,name=service,proto3,oneof"` // 服务上下线要求
}

func (*StatusUpdateReq_Service) isStatusUpdateReq_StatusUpdate() {}

var File_service_proto protoreflect.FileDescriptor

var file_service_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x72, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x22, 0x48, 0x0a, 0x16, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x72, 0x6f, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x72, 0x6f, 0x6c,
	0x65, 0x73, 0x22, 0x17, 0x0a, 0x15, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x39, 0x0a, 0x15, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x4d, 0x44, 0x35, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x28, 0x0a, 0x14, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x46, 0x69, 0x6c, 0x65, 0x4d, 0x44, 0x35, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x64, 0x35, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x64, 0x35,
	0x22, 0x3a, 0x0a, 0x16, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x2b, 0x0a, 0x15,
	0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x73, 0x0a, 0x13, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x65, 0x77, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x6e, 0x65, 0x77, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x1c, 0x0a, 0x09, 0x65, 0x78, 0x74, 0x72, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x78, 0x74, 0x72, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0xac,
	0x01, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x38, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x72, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x48, 0x00, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4e, 0x0a,
	0x0d, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x72, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x43,
	0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0d,
	0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x0e, 0x0a,
	0x0c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x22, 0x39, 0x0a,
	0x1d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x5b, 0x0a, 0x0f, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x38, 0x0a, 0x07, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x72,
	0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x48, 0x00, 0x52, 0x07, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x42, 0x0e, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x32, 0xd5, 0x02, 0x0a, 0x07, 0x52, 0x4d, 0x61, 0x73, 0x74, 0x65,
	0x72, 0x12, 0x54, 0x0a, 0x0f, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x1f, 0x2e, 0x72, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x72, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x51, 0x0a, 0x0e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x4d, 0x44, 0x35, 0x12, 0x1e, 0x2e, 0x72, 0x6d, 0x61, 0x73,
	0x74, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x4d,
	0x44, 0x35, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x72, 0x6d, 0x61, 0x73,
	0x74, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x4d,
	0x44, 0x35, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x56, 0x0a, 0x0f, 0x44, 0x6f,
	0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1f, 0x2e,
	0x72, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e,
	0x2e, 0x72, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61,
	0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00,
	0x30, 0x01, 0x12, 0x49, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x19, 0x2e, 0x72, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x18, 0x2e,
	0x72, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x0c, 0x5a,
	0x0a, 0x2e, 0x2f, 0x3b, 0x72, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData = file_service_proto_rawDesc
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_proto_rawDescData)
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_service_proto_goTypes = []interface{}{
	(*RegisterServiceRequest)(nil),        // 0: rmaster.RegisterServiceRequest
	(*RegisterServiceResult)(nil),         // 1: rmaster.RegisterServiceResult
	(*ServiceFileMD5Request)(nil),         // 2: rmaster.ServiceFileMD5Request
	(*ServiceFileMD5Result)(nil),          // 3: rmaster.ServiceFileMD5Result
	(*DownloadServiceRequest)(nil),        // 4: rmaster.DownloadServiceRequest
	(*DownloadServiceResult)(nil),         // 5: rmaster.DownloadServiceResult
	(*ServiceStatusChange)(nil),           // 6: rmaster.ServiceStatusChange
	(*StatusUpdateInfo)(nil),              // 7: rmaster.StatusUpdateInfo
	(*StatusUpdateInfoCertification)(nil), // 8: rmaster.StatusUpdateInfoCertification
	(*StatusUpdateReq)(nil),               // 9: rmaster.StatusUpdateReq
}
var file_service_proto_depIdxs = []int32{
	6, // 0: rmaster.StatusUpdateInfo.service:type_name -> rmaster.ServiceStatusChange
	8, // 1: rmaster.StatusUpdateInfo.certification:type_name -> rmaster.StatusUpdateInfoCertification
	6, // 2: rmaster.StatusUpdateReq.service:type_name -> rmaster.ServiceStatusChange
	0, // 3: rmaster.RMaster.RegisterService:input_type -> rmaster.RegisterServiceRequest
	2, // 4: rmaster.RMaster.ServiceFileMD5:input_type -> rmaster.ServiceFileMD5Request
	4, // 5: rmaster.RMaster.DownloadService:input_type -> rmaster.DownloadServiceRequest
	7, // 6: rmaster.RMaster.StatusUpdate:input_type -> rmaster.StatusUpdateInfo
	1, // 7: rmaster.RMaster.RegisterService:output_type -> rmaster.RegisterServiceResult
	3, // 8: rmaster.RMaster.ServiceFileMD5:output_type -> rmaster.ServiceFileMD5Result
	5, // 9: rmaster.RMaster.DownloadService:output_type -> rmaster.DownloadServiceResult
	9, // 10: rmaster.RMaster.StatusUpdate:output_type -> rmaster.StatusUpdateReq
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterServiceResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceFileMD5Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceFileMD5Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadServiceResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceStatusChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusUpdateInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusUpdateInfoCertification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_service_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*StatusUpdateInfo_Service)(nil),
		(*StatusUpdateInfo_Certification)(nil),
	}
	file_service_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*StatusUpdateReq_Service)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_rawDesc = nil
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RMasterClient is the client API for RMaster service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RMasterClient interface {
	RegisterService(ctx context.Context, in *RegisterServiceRequest, opts ...grpc.CallOption) (*RegisterServiceResult, error)
	ServiceFileMD5(ctx context.Context, in *ServiceFileMD5Request, opts ...grpc.CallOption) (*ServiceFileMD5Result, error)
	DownloadService(ctx context.Context, in *DownloadServiceRequest, opts ...grpc.CallOption) (RMaster_DownloadServiceClient, error)
	StatusUpdate(ctx context.Context, opts ...grpc.CallOption) (RMaster_StatusUpdateClient, error)
}

type rMasterClient struct {
	cc grpc.ClientConnInterface
}

func NewRMasterClient(cc grpc.ClientConnInterface) RMasterClient {
	return &rMasterClient{cc}
}

func (c *rMasterClient) RegisterService(ctx context.Context, in *RegisterServiceRequest, opts ...grpc.CallOption) (*RegisterServiceResult, error) {
	out := new(RegisterServiceResult)
	err := c.cc.Invoke(ctx, "/rmaster.RMaster/RegisterService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rMasterClient) ServiceFileMD5(ctx context.Context, in *ServiceFileMD5Request, opts ...grpc.CallOption) (*ServiceFileMD5Result, error) {
	out := new(ServiceFileMD5Result)
	err := c.cc.Invoke(ctx, "/rmaster.RMaster/ServiceFileMD5", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rMasterClient) DownloadService(ctx context.Context, in *DownloadServiceRequest, opts ...grpc.CallOption) (RMaster_DownloadServiceClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RMaster_serviceDesc.Streams[0], "/rmaster.RMaster/DownloadService", opts...)
	if err != nil {
		return nil, err
	}
	x := &rMasterDownloadServiceClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RMaster_DownloadServiceClient interface {
	Recv() (*DownloadServiceResult, error)
	grpc.ClientStream
}

type rMasterDownloadServiceClient struct {
	grpc.ClientStream
}

func (x *rMasterDownloadServiceClient) Recv() (*DownloadServiceResult, error) {
	m := new(DownloadServiceResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *rMasterClient) StatusUpdate(ctx context.Context, opts ...grpc.CallOption) (RMaster_StatusUpdateClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RMaster_serviceDesc.Streams[1], "/rmaster.RMaster/StatusUpdate", opts...)
	if err != nil {
		return nil, err
	}
	x := &rMasterStatusUpdateClient{stream}
	return x, nil
}

type RMaster_StatusUpdateClient interface {
	Send(*StatusUpdateInfo) error
	Recv() (*StatusUpdateReq, error)
	grpc.ClientStream
}

type rMasterStatusUpdateClient struct {
	grpc.ClientStream
}

func (x *rMasterStatusUpdateClient) Send(m *StatusUpdateInfo) error {
	return x.ClientStream.SendMsg(m)
}

func (x *rMasterStatusUpdateClient) Recv() (*StatusUpdateReq, error) {
	m := new(StatusUpdateReq)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RMasterServer is the server API for RMaster service.
type RMasterServer interface {
	RegisterService(context.Context, *RegisterServiceRequest) (*RegisterServiceResult, error)
	ServiceFileMD5(context.Context, *ServiceFileMD5Request) (*ServiceFileMD5Result, error)
	DownloadService(*DownloadServiceRequest, RMaster_DownloadServiceServer) error
	StatusUpdate(RMaster_StatusUpdateServer) error
}

// UnimplementedRMasterServer can be embedded to have forward compatible implementations.
type UnimplementedRMasterServer struct {
}

func (*UnimplementedRMasterServer) RegisterService(context.Context, *RegisterServiceRequest) (*RegisterServiceResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterService not implemented")
}
func (*UnimplementedRMasterServer) ServiceFileMD5(context.Context, *ServiceFileMD5Request) (*ServiceFileMD5Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServiceFileMD5 not implemented")
}
func (*UnimplementedRMasterServer) DownloadService(*DownloadServiceRequest, RMaster_DownloadServiceServer) error {
	return status.Errorf(codes.Unimplemented, "method DownloadService not implemented")
}
func (*UnimplementedRMasterServer) StatusUpdate(RMaster_StatusUpdateServer) error {
	return status.Errorf(codes.Unimplemented, "method StatusUpdate not implemented")
}

func RegisterRMasterServer(s *grpc.Server, srv RMasterServer) {
	s.RegisterService(&_RMaster_serviceDesc, srv)
}

func _RMaster_RegisterService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RMasterServer).RegisterService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rmaster.RMaster/RegisterService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RMasterServer).RegisterService(ctx, req.(*RegisterServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RMaster_ServiceFileMD5_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceFileMD5Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RMasterServer).ServiceFileMD5(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rmaster.RMaster/ServiceFileMD5",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RMasterServer).ServiceFileMD5(ctx, req.(*ServiceFileMD5Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _RMaster_DownloadService_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadServiceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RMasterServer).DownloadService(m, &rMasterDownloadServiceServer{stream})
}

type RMaster_DownloadServiceServer interface {
	Send(*DownloadServiceResult) error
	grpc.ServerStream
}

type rMasterDownloadServiceServer struct {
	grpc.ServerStream
}

func (x *rMasterDownloadServiceServer) Send(m *DownloadServiceResult) error {
	return x.ServerStream.SendMsg(m)
}

func _RMaster_StatusUpdate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RMasterServer).StatusUpdate(&rMasterStatusUpdateServer{stream})
}

type RMaster_StatusUpdateServer interface {
	Send(*StatusUpdateReq) error
	Recv() (*StatusUpdateInfo, error)
	grpc.ServerStream
}

type rMasterStatusUpdateServer struct {
	grpc.ServerStream
}

func (x *rMasterStatusUpdateServer) Send(m *StatusUpdateReq) error {
	return x.ServerStream.SendMsg(m)
}

func (x *rMasterStatusUpdateServer) Recv() (*StatusUpdateInfo, error) {
	m := new(StatusUpdateInfo)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _RMaster_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rmaster.RMaster",
	HandlerType: (*RMasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterService",
			Handler:    _RMaster_RegisterService_Handler,
		},
		{
			MethodName: "ServiceFileMD5",
			Handler:    _RMaster_ServiceFileMD5_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DownloadService",
			Handler:       _RMaster_DownloadService_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StatusUpdate",
			Handler:       _RMaster_StatusUpdate_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "service.proto",
}
